# Generated by Django 4.2.7 on 2024-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default='no brand', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
