# Generated by Django 4.2.7 on 2024-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_panel', '0002_products_brand_alter_products_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='media/products/'),
        ),
    ]
