# Generated by Django 4.2.7 on 2024-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('near_landmark', models.CharField(max_length=255)),
                ('gst', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.IntegerField()),
                ('ifc_code', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
