# Generated by Django 4.2.7 on 2024-01-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0002_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='user',
            new_name='user_name',
        ),
    ]
