# Generated by Django 4.2.7 on 2024-01-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0002_song_user_alter_song_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
