# Generated by Django 4.2.7 on 2024-01-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_panel', '0003_products_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing_app', '0003_remove_song_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_p', to='seller_panel.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
